name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, "3.0", 3.1]
        gemfile: [
          "gemfiles/6.1.gemfile",
          "gemfiles/7.0.gemfile",
        ]
        exclude:
          - ruby: 2.6
            gemfile: "gemfiles/7.0.gemfile"
          - ruby: 3.1
            gemfile: "gemfiles/6.1.gemfile"
    steps:
    - name: Install packages
      run: |
        sudo apt update -y
        sudo apt install -y libsqlite3-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rspec
      run: bundle exec rspec
